name: Release Swift Package

on:
  repository_dispatch:
    types: [release-cxxlibsample]

jobs:
  build_and_release:
    runs-on: macos-latest

    steps:
      - name: Checkout SwiftPackageXCFrameworkSample Repository
        uses: actions/checkout@v3

      - name: Set up environment variables
        run: |
          echo "CLONE_REPO_URL=https://github.com/NakaokaRei/CxxLibSample.git" >> $GITHUB_ENV
          echo "CLONE_REPO_DIR=CxxLibSample" >> $GITHUB_ENV
          echo "BUILD_SCRIPT=build_xcframework.sh" >> $GITHUB_ENV
          echo "XCFRAMEWORK_DIR=build/xcframework" >> $GITHUB_ENV
          echo "SWIFT_PACKAGE_DIR=." >> $GITHUB_ENV

      - name: Extract Tag Name
        id: extract_tag
        run: |
          TAG_REF="${{ github.event.client_payload.tag }}"  # "refs/tags/1.0.0"
          TAG_NAME="${TAG_REF#refs/tags/}"  # "1.0.0"
          echo "tag_name=${TAG_NAME}" >> $GITHUB_OUTPUT

      - name: Clone CxxLibSample Repository
        run: |
          git clone $CLONE_REPO_URL $CLONE_REPO_DIR

      - name: Make build_xcframework.sh executable
        run: chmod +x $CLONE_REPO_DIR/$BUILD_SCRIPT

      - name: Run build_xcframework.sh
        run: |
          cd $CLONE_REPO_DIR
          ./build_xcframework.sh

      - name: Verify XCFramework
        run: |
          if [ ! -d "$CLONE_REPO_DIR/$XCFRAMEWORK_DIR/CxxLibSample.xcframework" ]; then
            echo "Error: XCFramework not found at $CLONE_REPO_DIR/$XCFRAMEWORK_DIR/CxxLibSample.xcframework"
            exit 1
          fi

      - name: Archive XCFramework
        run: |
          TAG_NAME="${{ steps.extract_tag.outputs.tag_name }}"
          XCFRAMEWORK_PATH="$CLONE_REPO_DIR/$XCFRAMEWORK_DIR/CxxLibSample.xcframework"
          ZIP_PATH="build/CxxLibSample.xcframework-${TAG_NAME}.zip"
          mkdir -p build
          ditto -c -k --sequesterRsrc --keepParent "$XCFRAMEWORK_PATH" "$ZIP_PATH"

      - name: Upload XCFramework to GitHub Releases
        uses: softprops/action-gh-release@v2
        with:
          files: build/CxxLibSample.xcframework-${{ steps.extract_tag.outputs.tag_name }}.zip
          tag_name: ${{ steps.extract_tag.outputs.tag_name }}
          name: ${{ steps.extract_tag.outputs.tag_name }}
          draft: true
          token: ${{ secrets.PAT_GITHUB }}

      - name: Get Release Asset URL and Checksum
        id: get_assets
        env:
          GH_TOKEN: ${{ secrets.PAT_GITHUB }} 
        run: |
          TAG_NAME="${{ steps.extract_tag.outputs.tag_name }}"
          ASSET_URL=$(gh release view "$TAG_NAME" --json assets --jq '.assets[0].browser_download_url')
          echo "zipUrl=${ASSET_URL}" >> $GITHUB_ENV

          CHECKSUM=$(shasum -a 256 build/CxxLibSample.xcframework-${TAG_NAME}.zip | awk '{print $1}')
          echo "checksum=${CHECKSUM}" >> $GITHUB_ENV

          echo "zipUrl=${ASSET_URL}" >> $GITHUB_OUTPUT
          echo "checksum=${CHECKSUM}" >> $GITHUB_OUTPUT

      - name: Update Package.swift
        run: |
          TAG_NAME="${{ steps.extract_tag.outputs.tag_name }}"
          XCFRAMEWORK_VERSION="${TAG_NAME}"

          git checkout -b update-package-swift-${TAG_NAME}

          sed -i '' 's#let zipUrl = ".*"#let zipUrl = "${{ steps.get_assets.outputs.zipUrl }}.zip"#' Package.swift
          sed -i '' 's#let checksum = ".*"#let checksum = "${{ steps.get_assets.outputs.checksum }}"#' Package.swift

          git add Package.swift
          git commit -m "chore: update Package.swift for version ${XCFRAMEWORK_VERSION}"

      - name: Configure Git for Push
        run: |
          git config user.name "NakaoakRei"
          git config user.email "reideeplearning@gmail.com"
          git remote set-url origin https://x-access-token:${{ secrets.PAT_GITHUB }}@github.com/NakaokaRei/SwiftPackageXCFrameworkSample.git
      
      - name: Push changes to remote
        run: |
          TAG_NAME="${{ steps.extract_tag.outputs.tag_name }}"
          git push origin update-package-swift-${TAG_NAME}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.PAT_GITHUB }}
          branch: update-package-swift-${{ steps.extract_tag.outputs.tag_name }}
          title: "chore: update Package.swift for version ${{ steps.extract_tag.outputs.tag_name }}"
          body: |
            This PR updates `Package.swift` to use version ${{ steps.extract_tag.outputs.tag_name }} of `CxxLibSample.xcframework`.
          base: main
          labels: 'release'
          add-paths: Package.swift
